In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
dataset.shape

(399, 28)

In [6]:
dataset.value_counts()

age   bp         al   su   bgr         bu          sc        sod         pot       hrmo       pcv        wc           rc        sg_b  sg_c  sg_d  sg_e  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes
2.0   76.459948  3.0  0.0  148.112676  57.482105   3.077356  137.528754  4.627244  12.518156  38.868902  8408.191126  4.705597  0     1     0     0     1           0          0            0           0        0       0        1          1       0        1                     1
61.0  90.000000  0.0  2.0  148.112676  57.482105   3.077356  137.528754  4.627244  12.518156  38.868902  9800.000000  4.705597  0     0     1     0     1           1          0            0           0        1       0        0          0       1        1                     1
      80.000000  0.0  4.0  360.000000  19.000000   0.700000  137.000000  4.400000  15.200000  44.000000  8300.000000  5.200000  0     0     1     0     1           1          0            0           1        1       0        1          0       0        1                     1
                      0.0  131.000000  23.000000   0.800000  140.000000  4.100000  11.300000  35.000000  8408.191126  4.705597  0     0     0     0     1           1          0            0           0        0       0        1          0       0        1                     1
      70.000000  0.0  0.0  133.000000  38.000000   1.000000  142.000000  3.600000  13.700000  47.000000  9200.000000  4.900000  1     0     0     0     1           1          0            0           0        0       0        1          0       0        0                     1
                                                                                                                                                                                                                                                                                   ..
46.0  90.000000  0.0  0.0  213.000000  68.000000   2.800000  146.000000  6.300000  9.300000   38.868902  8408.191126  4.705597  0     0     0     0     1           1          0            0           1        1       0        1          0       0        1                     1
      80.000000  0.0  0.0  160.000000  40.000000   2.000000  140.000000  4.100000  9.000000   27.000000  8100.000000  3.200000  0     1     0     0     1           1          0            0           1        0       0        0          0       1        1                     1
      70.000000  1.0  0.0  150.000000  111.000000  6.100000  131.000000  3.700000  7.500000   27.000000  8408.191126  4.705597  0     0     1     0     0           1          0            0           0        0       0        1          0       1        1                     1
                 0.0  0.0  100.000000  47.000000   0.500000  142.000000  3.500000  16.400000  43.000000  5700.000000  6.500000  1     0     0     0     1           1          0            0           0        0       0        1          0       0        0                     1
90.0  90.000000  1.0  0.0  139.000000  89.000000   3.000000  140.000000  4.100000  12.000000  37.000000  7900.000000  3.900000  1     0     0     0     1           1          0            0           1        1       0        1          0       0        1                     1
Length: 399, dtype: int64

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [8]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [11]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# x_train=sc.fit_transform(x_train)
# y_train=sc.fit(y_train)

In [12]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)
from sklearn.model_selection import GridSearchCV
grid_params={'criterion':['gini', 'entropy', 'log_loss'],
            'splitter':['best', 'random'],
            'max_features':['auto', 'sqrt', 'log2']
            }
grid=GridSearchCV(classifier,grid_params,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)
# criterion{“gini”, “entropy”, “log_loss”}
# splitter{“best”, “random”}
# max_features{“auto”, “sqrt”, “log2”}

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [13]:
result=grid.cv_results_
result

{'mean_fit_time': array([0.14930673, 0.07275252, 0.00899286, 0.01259227, 0.01059179,
        0.02398467, 0.05496407, 0.05716486, 0.01938715, 0.01918745,
        0.01239095, 0.00759397, 0.04117198, 0.07714982, 0.00859489,
        0.00799427, 0.00819306, 0.01299071]),
 'std_fit_time': array([0.06058395, 0.05857917, 0.00063256, 0.00773147, 0.00422233,
        0.00703905, 0.00141296, 0.00336852, 0.00079959, 0.00039983,
        0.00581485, 0.00048908, 0.00039938, 0.07036302, 0.00079919,
        0.00063226, 0.00039945, 0.00539953]),
 'mean_score_time': array([0.01159339, 0.01759033, 0.02658277, 0.01359024, 0.02138767,
        0.04956799, 0.03457985, 0.03757634, 0.03757672, 0.0383759 ,
        0.01818752, 0.02358499, 0.01039457, 0.01559157, 0.01199136,
        0.01758885, 0.02078691, 0.03178134]),
 'std_score_time': array([0.00174301, 0.01035966, 0.0137698 , 0.00492021, 0.01035971,
        0.01308593, 0.00534895, 0.01016424, 0.00872655, 0.00861172,
        0.01113465, 0.0135948 , 0.00079918, 0.01119258, 0.004514  ,
        0.01126363, 0.01143654, 0.02014127]),
 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'log_loss', 'log_loss', 'log_loss',
                    'log_loss', 'log_loss', 'log_loss'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                    'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto', 'auto',
                    'sqrt', 'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'gini', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'gini', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'gini', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'gini', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'entropy', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'entropy', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'log_loss', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'log_loss', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'log_loss', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'log_loss', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'log_loss', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'log_loss', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([0.96428571, 0.9822211 , 0.96457219, 0.91202946, 0.9822211 ,
        1.        , 0.94701493, 1.        , 0.91169154, 0.96457219,
        0.96457219, 0.9822211 , 0.96428571, 0.9822211 , 0.92914439,
        0.96457219, 0.96428571, 0.96388889]),
 'split1_test_score': array([0.89285714, 0.96428571, 0.92857143, 0.96388889, 0.94546891,
        0.9822211 , 0.9466633 , 0.96428571, 0.96457219, 0.92914439,
        0.9466633 , 0.9822211 , 0.94546891, 0.92857143, 0.92777778,
        1.        , 0.89285714, 0.96457219]),
 'split2_test_score': array([0.91202946, 0.94615252, 0.89453125, 0.91169154, 0.9822211 ,
        1.        , 0.91169154, 0.98205084, 0.91169154, 0.92914439,
        0.9822211 , 0.94701493, 0.92951252, 1.        , 0.91202946,
        0.96457219, 0.9822211 , 0.98205084]),
 'split3_test_score': array([0.92914439, 0.9822211 , 0.96428571, 0.96457219, 0.94546891,
        0.9822211 , 0.92777778, 0.94701493, 0.92914439, 0.9822211 ,
        0.92914439, 0.9822211 , 0.96388889, 0.9822211 , 0.96428571,
        0.96428571, 1.        , 0.92777778]),
 'split4_test_score': array([0.9817282 , 0.9817282 , 0.96363636, 0.9817282 , 0.94518461,
        0.96363636, 1.        , 1.        , 0.98189391, 0.9817282 ,
        0.98189391, 0.96324675, 0.96363636, 0.96324675, 0.96363636,
        0.9817282 , 1.        , 0.98189391]),
 'mean_test_score': array([0.93600898, 0.97132173, 0.94311939, 0.94678206, 0.96011293,
        0.98561571, 0.94662951, 0.9786703 , 0.93979872, 0.95736205,
        0.96089898, 0.97138499, 0.95335848, 0.97125208, 0.93937474,
        0.97503166, 0.96787279, 0.96403672]),
 'std_test_score': array([0.03278427, 0.01434491, 0.02793433, 0.02922141, 0.01805154,
        0.01356432, 0.02974763, 0.02064131, 0.02856316, 0.02390038,
        0.02059088, 0.01422951, 0.01390542, 0.02430146, 0.02095756,
        0.01416007, 0.03977538, 0.01979094]),
 'rank_test_score': array([18,  5, 15, 13, 10,  1, 14,  2, 16, 11,  9,  4, 12,  6, 17,  3,  7,
         8])}

In [14]:
grid_pred=grid.predict(x_test)
grid_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0], dtype=uint8)

In [15]:
solution=grid.best_params_
solution

{'criterion': 'gini', 'max_features': 'log2', 'splitter': 'random'}

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_pred)
print(cm)

[[45  0]
 [ 4 71]]

In [17]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        45
           1       1.00      0.95      0.97        75

    accuracy                           0.97       120
   macro avg       0.96      0.97      0.97       120
weighted avg       0.97      0.97      0.97       120

In [18]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.149307,0.060584,0.011593,0.001743,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.964286,0.892857,0.912029,0.929144,0.981728,0.936009,0.032784,18
1,0.072753,0.058579,0.017590,0.010360,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.982221,0.964286,0.946153,0.982221,0.981728,0.971322,0.014345,5
2,0.008993,0.000633,0.026583,0.013770,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.964572,0.928571,0.894531,0.964286,0.963636,0.943119,0.027934,15
3,0.012592,0.007731,0.013590,0.004920,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.912029,0.963889,0.911692,0.964572,0.981728,0.946782,0.029221,13
4,0.010592,0.004222,0.021388,0.010360,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.982221,0.945469,0.982221,0.945469,0.945185,0.960113,0.018052,10
5,0.023985,0.007039,0.049568,0.013086,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.982221,1.000000,0.982221,0.963636,0.985616,0.013564,1
6,0.054964,0.001413,0.034580,0.005349,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.947015,0.946663,0.911692,0.927778,1.000000,0.946630,0.029748,14
7,0.057165,0.003369,0.037576,0.010164,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",1.000000,0.964286,0.982051,0.947015,1.000000,0.978670,0.020641,2
8,0.019387,0.000800,0.037577,0.008727,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.911692,0.964572,0.911692,0.929144,0.981894,0.939799,0.028563,16
9,0.019187,0.000400,0.038376,0.008612,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.964572,0.929144,0.929144,0.982221,0.981728,0.957362,0.023900,11
10,0.012391,0.005815,0.018188,0.011135,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.964572,0.946663,0.982221,0.929144,0.981894,0.960899,0.020591,9
11,0.007594,0.000489,0.023585,0.013595,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.982221,0.947015,0.982221,0.963247,0.971385,0.014230,4
12,0.041172,0.000399,0.010395,0.000799,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",0.964286,0.945469,0.929513,0.963889,0.963636,0.953358,0.013905,12
13,0.077150,0.070363,0.015592,0.011193,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",0.982221,0.928571,1.000000,0.982221,0.963247,0.971252,0.024301,6
14,0.008595,0.000799,0.011991,0.004514,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.929144,0.927778,0.912029,0.964286,0.963636,0.939375,0.020958,17
15,0.007994,0.000632,0.017589,0.011264,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.964572,1.000000,0.964572,0.964286,0.981728,0.975032,0.014160,3
16,0.008193,0.000399,0.020787,0.011437,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.964286,0.892857,0.982221,1.000000,1.000000,0.967873,0.039775,7
17,0.012991,0.005400,0.031781,0.020141,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.963889,0.964572,0.982051,0.927778,0.981894,0.964037,0.019791,8

In [19]:
print("the result is:{}".format(grid.best_params_))

the result is:{'criterion': 'gini', 'max_features': 'log2', 'splitter': 'random'}

In [24]:
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(y_test, grid.predict_proba(x_test)[:,1])
roc_score

0.9733333333333334

In [21]:
# import pickle as pkl
# file_name="multinominal_nb_final.sav"

In [22]:
# pkl.dump(classifier,open(file_name, "wb"))

In [23]:
# # # 'age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
# #        'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
# #        'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
# #        'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'

# load_file=pkl.load(open(file_name, "rb"))
# age=int(input("Enter your Age: "))
# bp=int(input("Enter your Blood pressure: "))
# al=int(input("Enter your AL value: "))
# su=int(input("Enter your SU value: "))
# bgr=int(input("Enter your BGR value: "))
# bu=int(input("Enter your BU value: "))
# sc=int(input("Enter your SC value: "))
# sod=int(input("Enter your SOD value: "))
# pot=int(input("Enter your POT value: "))
# hrmo=int(input("Enter your HRMO value: "))
# pcv=int(input("Enter your PCV value: "))
# wc=int(input("Enter your WC value: "))
# rc=int(input("Enter your RC value: "))
# sg_b=int(input("Enter your SG_B value: "))
# sg_c=int(input("Enter your SG_C value: "))
# sg_d=int(input("Enter your SG_D value: "))
# sg_e=int(input("Enter your SG_E value: "))
# rbc=int(input("Enter your RBC value(Normal=1/abnormal=0): "))
# pc=int(input("Enter your PC value(Normal=1/abnormal=0): "))
# pcc=int(input("Enter your PCC value(Present=1/Absent=0): "))
# ba=int(input("Enter your BA value(Present=1/Absent=0): "))
# htn=int(input("Enter your HTN value(Yes=1/No=0): "))
# dm=int(input("Enter your DM value(Yes=1/No=0): "))
# cad=int(input("Enter your CAD value(Yes=1/No=0)): "))
# appet=int(input("Enter your APPET value(Yes=1/No=0): "))
# pe=int(input("Enter your PE value(Yes=1/No=0): "))
# ana=int(input("Enter your ANA value(Yes=1/No=0): "))

# answer=load_file.predict([[age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ana]])
# print("The Chronic Kidney Disease (Yes=1/No=0): {}".format(answer))