In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
dataset.shape

(399, 28)

In [6]:
dataset.value_counts()

age   bp         al   su   bgr         bu          sc        sod         pot       hrmo       pcv        wc           rc        sg_b  sg_c  sg_d  sg_e  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes
2.0   76.459948  3.0  0.0  148.112676  57.482105   3.077356  137.528754  4.627244  12.518156  38.868902  8408.191126  4.705597  0     1     0     0     1           0          0            0           0        0       0        1          1       0        1                     1
61.0  90.000000  0.0  2.0  148.112676  57.482105   3.077356  137.528754  4.627244  12.518156  38.868902  9800.000000  4.705597  0     0     1     0     1           1          0            0           0        1       0        0          0       1        1                     1
      80.000000  0.0  4.0  360.000000  19.000000   0.700000  137.000000  4.400000  15.200000  44.000000  8300.000000  5.200000  0     0     1     0     1           1          0            0           1        1       0        1          0       0        1                     1
                      0.0  131.000000  23.000000   0.800000  140.000000  4.100000  11.300000  35.000000  8408.191126  4.705597  0     0     0     0     1           1          0            0           0        0       0        1          0       0        1                     1
      70.000000  0.0  0.0  133.000000  38.000000   1.000000  142.000000  3.600000  13.700000  47.000000  9200.000000  4.900000  1     0     0     0     1           1          0            0           0        0       0        1          0       0        0                     1
                                                                                                                                                                                                                                                                                   ..
46.0  90.000000  0.0  0.0  213.000000  68.000000   2.800000  146.000000  6.300000  9.300000   38.868902  8408.191126  4.705597  0     0     0     0     1           1          0            0           1        1       0        1          0       0        1                     1
      80.000000  0.0  0.0  160.000000  40.000000   2.000000  140.000000  4.100000  9.000000   27.000000  8100.000000  3.200000  0     1     0     0     1           1          0            0           1        0       0        0          0       1        1                     1
      70.000000  1.0  0.0  150.000000  111.000000  6.100000  131.000000  3.700000  7.500000   27.000000  8408.191126  4.705597  0     0     1     0     0           1          0            0           0        0       0        1          0       1        1                     1
                 0.0  0.0  100.000000  47.000000   0.500000  142.000000  3.500000  16.400000  43.000000  5700.000000  6.500000  1     0     0     0     1           1          0            0           0        0       0        1          0       0        0                     1
90.0  90.000000  1.0  0.0  139.000000  89.000000   3.000000  140.000000  4.100000  12.000000  37.000000  7900.000000  3.900000  1     0     0     0     1           1          0            0           1        1       0        1          0       0        1                     1
Length: 399, dtype: int64

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [8]:
dependent=dataset[['classification_yes']]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [11]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# x_train=sc.fit_transform(x_train)
# y_train=sc.fit(y_train)

In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)
from sklearn.model_selection import GridSearchCV
grid_params={'max_features':['sqrt', 'log2', None],
             'criterion':['gini', 'entropy', 'log_loss']
            }
grid=GridSearchCV(classifier,grid_params,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)
# max_features{“sqrt”, “log2”, None}
# criterion{“gini”, “entropy”, “log_loss”}

C:\Users\jayac\AppData\Local\Temp\ipykernel_3544\3672444190.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(x_train,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2', None]},
             scoring='f1_weighted', verbose=3)

In [14]:
result=grid.cv_results_
result

{'mean_fit_time': array([0.35658035, 0.37716689, 0.49169536, 0.90544157, 0.35937734,
        0.45911517, 0.66818738, 0.68737421, 0.47350607]),
 'std_fit_time': array([0.0057011 , 0.0067367 , 0.07711517, 0.17184323, 0.01190177,
        0.00621307, 0.20988683, 0.2772198 , 0.00862937]),
 'mean_score_time': array([0.03437767, 0.03537707, 0.04557266, 0.06435947, 0.03677731,
        0.03457885, 0.0723557 , 0.0415741 , 0.03417983]),
 'std_score_time': array([0.00241374, 0.00135531, 0.02319463, 0.02448497, 0.0041159 ,
        0.00272521, 0.03078816, 0.02219985, 0.00248013]),
 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'entropy', 'entropy',
                    'entropy', 'log_loss', 'log_loss', 'log_loss'],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['sqrt', 'log2', None, 'sqrt', 'log2', None, 'sqrt',
                    'log2', None],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'gini', 'max_features': 'sqrt'},
  {'criterion': 'gini', 'max_features': 'log2'},
  {'criterion': 'gini', 'max_features': None},
  {'criterion': 'entropy', 'max_features': 'sqrt'},
  {'criterion': 'entropy', 'max_features': 'log2'},
  {'criterion': 'entropy', 'max_features': None},
  {'criterion': 'log_loss', 'max_features': 'sqrt'},
  {'criterion': 'log_loss', 'max_features': 'log2'},
  {'criterion': 'log_loss', 'max_features': None}],
 'split0_test_score': array([1.        , 1.        , 0.96428571, 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.98205084]),
 'split1_test_score': array([0.96388889, 0.94546891, 0.92777778, 0.94546891, 0.98205084,
        0.92777778, 0.96388889, 0.94546891, 0.92777778]),
 'split2_test_score': array([0.94701493, 0.96457219, 0.89453125, 0.94701493, 0.9822211 ,
        0.89453125, 0.92951252, 0.96457219, 0.89453125]),
 'split3_test_score': array([0.98205084, 0.98205084, 0.92674253, 0.98205084, 0.96428571,
        0.92674253, 0.96428571, 0.96428571, 0.90911486]),
 'split4_test_score': array([1.       , 0.9817282, 0.9817282, 1.       , 1.       , 0.9817282,
        1.       , 1.       , 0.9817282]),
 'mean_test_score': array([0.97859093, 0.97476403, 0.9390131 , 0.97490694, 0.98571153,
        0.94615595, 0.97153742, 0.97486536, 0.93904059]),
 'std_test_score': array([0.02069716, 0.01844196, 0.03072041, 0.02431016, 0.01336391,
        0.03884408, 0.02644775, 0.02165885, 0.03653928]),
 'rank_test_score': array([2, 5, 9, 3, 1, 7, 6, 4, 8])}

In [15]:
grid_pred=grid.predict(x_test)
grid_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0], dtype=uint8)

In [16]:
solution=grid.best_params_
solution

{'criterion': 'entropy', 'max_features': 'log2'}

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_pred)
print(cm)

[[45  0]
 [ 1 74]]

In [18]:
# from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [21]:
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(y_test, grid.predict_proba(x_test)[:,1])
roc_score

1.0

In [25]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.356580,0.005701,0.034378,0.002414,gini,sqrt,"{'criterion': 'gini', 'max_features': 'sqrt'}",1.000000,0.963889,0.947015,0.982051,1.000000,0.978591,0.020697,2
1,0.377167,0.006737,0.035377,0.001355,gini,log2,"{'criterion': 'gini', 'max_features': 'log2'}",1.000000,0.945469,0.964572,0.982051,0.981728,0.974764,0.018442,5
2,0.491695,0.077115,0.045573,0.023195,gini,None,"{'criterion': 'gini', 'max_features': None}",0.964286,0.927778,0.894531,0.926743,0.981728,0.939013,0.030720,9
3,0.905442,0.171843,0.064359,0.024485,entropy,sqrt,"{'criterion': 'entropy', 'max_features': 'sqrt'}",1.000000,0.945469,0.947015,0.982051,1.000000,0.974907,0.024310,3
4,0.359377,0.011902,0.036777,0.004116,entropy,log2,"{'criterion': 'entropy', 'max_features': 'log2'}",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,1
5,0.459115,0.006213,0.034579,0.002725,entropy,None,"{'criterion': 'entropy', 'max_features': None}",1.000000,0.927778,0.894531,0.926743,0.981728,0.946156,0.038844,7
6,0.668187,0.209887,0.072356,0.030788,log_loss,sqrt,"{'criterion': 'log_loss', 'max_features': 'sqrt'}",1.000000,0.963889,0.929513,0.964286,1.000000,0.971537,0.026448,6
7,0.687374,0.277220,0.041574,0.022200,log_loss,log2,"{'criterion': 'log_loss', 'max_features': 'log2'}",1.000000,0.945469,0.964572,0.964286,1.000000,0.974865,0.021659,4
8,0.473506,0.008629,0.034180,0.002480,log_loss,None,"{'criterion': 'log_loss', 'max_features': None}",0.982051,0.927778,0.894531,0.909115,0.981728,0.939041,0.036539,8

In [26]:
print("the result is:{}".format(grid.best_params_))

the result is:{'criterion': 'entropy', 'max_features': 'log2'}

In [27]:
import pickle as pkl
file_name="Random_Forest_final.sav"

In [28]:
pkl.dump(classifier,open(file_name, "wb"))

In [29]:
# # 'age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
#        'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
#        'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
#        'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'

load_file=pkl.load(open(file_name, "rb"))
age=int(input("Enter your Age: "))
bp=int(input("Enter your Blood pressure: "))
al=int(input("Enter your AL value: "))
su=int(input("Enter your SU value: "))
bgr=int(input("Enter your BGR value: "))
bu=int(input("Enter your BU value: "))
sc=int(input("Enter your SC value: "))
sod=int(input("Enter your SOD value: "))
pot=int(input("Enter your POT value: "))
hrmo=int(input("Enter your HRMO value: "))
pcv=int(input("Enter your PCV value: "))
wc=int(input("Enter your WC value: "))
rc=int(input("Enter your RC value: "))
sg_b=int(input("Enter your SG_B value: "))
sg_c=int(input("Enter your SG_C value: "))
sg_d=int(input("Enter your SG_D value: "))
sg_e=int(input("Enter your SG_E value: "))
rbc=int(input("Enter your RBC value(Normal=1/abnormal=0): "))
pc=int(input("Enter your PC value(Normal=1/abnormal=0): "))
pcc=int(input("Enter your PCC value(Present=1/Absent=0): "))
ba=int(input("Enter your BA value(Present=1/Absent=0): "))
htn=int(input("Enter your HTN value(Yes=1/No=0): "))
dm=int(input("Enter your DM value(Yes=1/No=0): "))
cad=int(input("Enter your CAD value(Yes=1/No=0)): "))
appet=int(input("Enter your APPET value(Yes=1/No=0): "))
pe=int(input("Enter your PE value(Yes=1/No=0): "))
ana=int(input("Enter your ANA value(Yes=1/No=0): "))

answer=load_file.predict([[age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ana]])
print("The Chronic Kidney Disease (Yes=1/No=0): {}".format(answer))

Enter your Age: 54
Enter your Blood pressure: 130
Enter your AL value: 43
Enter your SU value: 87
Enter your BGR value: 65
Enter your BU value: 76
Enter your SC value: 45
Enter your SOD value: 34
Enter your POT value: 76
Enter your HRMO value: 56
Enter your PCV value: 98
Enter your WC value: 23
Enter your RC value: 765
Enter your SG_B value: 76
Enter your SG_C value: 87
Enter your SG_D value: 98
Enter your SG_E value: 76
Enter your RBC value(Normal=1/abnormal=0): 0
Enter your PC value(Normal=1/abnormal=0): 1
Enter your PCC value(Present=1/Absent=0): 0
Enter your BA value(Present=1/Absent=0): 1
Enter your HTN value(Yes=1/No=0): 0
Enter your DM value(Yes=1/No=0): 1
Enter your CAD value(Yes=1/No=0)): 0
Enter your APPET value(Yes=1/No=0): 1
Enter your PE value(Yes=1/No=0): 0
Enter your ANA value(Yes=1/No=0): 1

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

The Chronic Kidney Disease (Yes=1/No=0): [1]